dist: trusty

sudo: false

language: node_js

node_js:
  - 8 # runtime used within Firebase functions

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod

cache:
  directories:
    - $HOME/.npm

install:
  - npm i

script:
  - npm run createConfig # create env specific src/config.js
  - npm run lint
  - npm run test
  - npm run build
  - npm run deploy # deploy if branch matches a project in .firebaserc

addons:
  code_climate:
    repo_token: $CODE_CLIMATE


